### ISSUE TITLE
Use fork without data races?

### ISSUE THREAD

**Issue by International** [Adron/datadiluvium#22]
Hi Adron!
I've also used fake in a project recently. One of the issues I've stumbled upon are race conditions ( might pop up if you use `go run --race` ). In my case, they were fixed by switching to jackc's fork https://github.com/jackc/fake . The issue is also described here: https://github.com/icrowley/fake/pull/1

**Comment by Adron** [comment]
Ah, thanks for the info @International. Much appreciated.
