### ISSUE TITLE
Create JSON Format for Key Value

### ISSUE THREAD

**Issue by Adron** [Adron/datadiluvium#33]
Hey @Lenadroid could you take a look at this? I'm not sure the idea stands out from the schema below that well, but trying to determine how to break out the data in the schema to describe how to generate data. What are your thoughts?

Basic first draft here...

```
  {
    "datastore": "cassandra",
    "genrows": "225",
    "connection": "the-redis-cassandra-string",
    "generate": [
      {
        "name": "key",
        "data": "uuid"
      },{
        "name": "value",
        "data": "string"
      }
    ]
  },
   ... other schema here ...
]
```

**Comment by lenadroid** [comment]
Hey,

Are you asking if the format is good? @Adron

**Comment by Adron** [comment]
Curious what, since you're familiar with Cassandra & related key value style formats, what would look like a good format to generate for a Cassandra database. For example, what is some familiar data that would be stored in Cassandra that Cassandra is good for use with?

**Comment by lenadroid** [comment]
Okay. In Cassandra, you also define which columns you are going to have, and which type each column has. You can also mark a column/columns as a partition key. Usually you choose partition key for the table based on how data is queried. For example, if you have 2 types of queries, it might be inefficient to use same table to fetch data from. For search to be fast you would have two tables, each optimized for each of corresponding query type. You can also mark columns as clustering columns. That means, your data is stored within partition and ordered by that column.

I think what you're trying to do with various DB formats is generate data corresponding to DB schema. I am not sure to which extent are you going to populate the generated database...
Are you going to generate just one table? some number of tables? are the tables connected in any way? what type of relationship do these tables have between each other?

I think it would be helpful to look not just at a table structure for each DB you're planning to support. But also for architectural/structural design in which these tables are composed. I'm talking: relational, key-value, graph, etc.

For example. When you create a table in relational database, you can create it in a "normalized form" way, where you have relationship between tables based on a foreign key. 

In Cassandra, there are it's own relationship patterns. Here is a useful link on that topic: https://academy.datastax.com/resources/ds220-data-modeling
